### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by dtorvi** [TylerLo416/CSE110-sp21-group20#25]
Basic Build with three images, login button, sign up form, and randomize button

**Comment by SheepTester** [comment]
I think we've decided to do away with login/sign up

The three images + randomize button were implemented by [ec4c019824016a851db03ac3e4e7af1597ff3e28](https://github.com/cse110-sp23-group20/fortune-teller/commit/ec4c019824016a851db03ac3e4e7af1597ff3e28)
