### ISSUE TITLE
Fortune Cookie: Add hyperlinks to the other pages as well as the main page

### ISSUE THREAD

**Issue by bsalvania** [TylerLo416/CSE110-sp21-group20#33]

**Comment by bsalvania** [comment]
We have a navigation bar set up, just need links to other pages

**Comment by SheepTester** [comment]
Added in https://github.com/cse110-sp23-group20/fortune-teller/commit/f8f1ebb2be1bf01a9beb997bb1b80564bf1e5252 and links were updated in https://github.com/cse110-sp23-group20/fortune-teller/commit/af1800ec7cdbdf86aaf63f87a9f1007d38564d2c
